### ISSUE TITLE
Question: Json File Parameters

### ISSUE THREAD

**Issue by michaelcurry** [ScripterSugar/wdfp-extractor#14]
I would first like to that you for making this application,  it truly has saved me MANY hours of work and frustration. 

I was wondering if you by changes know (or know how to determine) the "names" / "reasons" for the data exported in the Json files.  For example the `characters.json`  (below is an example of what I Think might be correct, but am still missing a lot of the fields).  Have you ever gone through and looked into these files?  

Side note: If this is a Data Mining (Manual) process that you have not looked into as of yet - I would be happy to document and share my findings, if where is somewhere in the Repo/Wiki you would like to aggregate this information.

```
"1": [
    // character string (matches assets folder)
    "alk",
    // ???
    "1",
    // Stars
    "4",
    // ???
    "0",
    // Race
    "Human",
    // ???
    "",
    // ???
    "0",
    // Gender
    "Male",
    // character string (matches assets folder) Duplicate ???
    "alk",
    // ???
    "1",
    // Leader (Ability)
    "Path to the Stars",
    // Ability 1
    "11",
    // Ability 2
    "12",
    // Ability 3
    "13",
    // Ability 4
    "14",
    // Ability 5
    "15",
    // Ability 6
    "16",
    // Ability (MB2 ???)
    "2",
    // Role
    "Balance",
    // Character ID
    "1",
    // ???
    "(None)",
    // ???
    "1",
    // ???
    "false",
    // ???
    "true",
    // ???
    "1",
    // ???
    "1",
    // ???
    "",
    // ???
    ""
],
```

**Comment by ScripterSugar** [comment]
To ascertain the meaning of each data in master table (aka orderedmap) files, you need to first look into the SWF scripts that import and actually uses them. So you need to pull the SWF and fully decompile it and extract all the needed .as files from decompilation. (FYI: You can do this with my tool, but doing this for JP client with my tool currently requires rooted device although its feasible without root permission. If you don't have rooted device and still want to decompile SWF out of JP client, you'll first need to unpack apk and find the SWF file packed inside APK and then you can manually decompile it with [FFDEC](https://github.com/jindrapetrik/jpexs-decompiler))

anyway, back to the point, we need to locate the specific .as file that references your designated master table file. there's not many ways to do this since all the .as files are obfuscated and files names are in really messy format.

So here's the way I do it when needed.

Let's say we want to look for /box_gacha/box_reward.orderedmap file. I first look into the scripts/boot_ffc6.as file which contains all the master table imports and class matching. Then I search the master table file name within boot_ffc6.as so I can get the obfuscated name of the class that imports the initiator class. You'll get the result like below.

![image](https://user-images.githubusercontent.com/19164553/192708813-3911317d-9c8d-42aa-8800-9f057fb024b6.png)

you can see the field `clazz: §㆒§.§―§.§⁃§.§⼀§.ᅳ.§⁃§.§–§.§‑§.§⼀§.§‑§.§⎯§.§‒§.§⼀§.ｰ.ᅳ.int`. This is the specific class where they import your orderedmap file and throw them into initiator classes, and these initiator classes are precisely the implementation we want to look at. 

 Now lets locate to the .as file for above class we found. For this example you want to search `package §㆒§.§―§.§⁃§.§⼀§.ᅳ.§⁃§.§–§.§‑§.§⼀§.§‑§.§⎯§.§‒§.§⼀§.ｰ.ᅳ` in your own IDE so we can find the file has this string.

![image](https://user-images.githubusercontent.com/19164553/192709844-806c320a-6a91-4a5e-b8f2-e125342c67f8.png)

As a result, you'll find the .as file that looks like above image. Focus on the get_data() method of the class. We want to copy the last-appearing class name in the return statement, which is name of initiator class where data refinement will happen inside.
![image](https://user-images.githubusercontent.com/19164553/192710103-87998f01-9e50-405b-8403-a1ecce79fea3.png)

Like we did before now we want to search for it again `package ー.§−§.§‑§.§–§.§‒§.§㆒§.§−§.§—§.§‑§.§⁃§.§‐§.§–§.§−§.§—§.§‐§`
and you'll get the file, with the int() method somewhat look like below image.
![image](https://user-images.githubusercontent.com/19164553/192710425-1728e601-146c-493a-b43f-4fdbf501d868.png)

Voila! int() method will be longer or shorter than the example depending on the cases. what we want to see is how they're parsing the data inside this method. you can see some variable names are in actual human readable format. So we can safely assume they're mapped like this

![image](https://user-images.githubusercontent.com/19164553/192710991-b6fe87b9-60e1-4262-94c3-162943881a63.png)

Sometimes initiator classes use more complex way of parsing and you may need to locate into several more referenced scripts but basics are same. 

Also, contribution for documentation is always welcome! you can make PR with improved documentation if you want to contribute :) I recommend you to split such documentation and put it on the separated .md file in repository root and link them into README.md so we can locate to them more easily.

**Comment by michaelcurry** [comment]
Wow - You are amazing for providing such a detailed write up.  I have time set aside this weekend for this, and will respond here if I have any follow-up questions.

Once I have more understanding and results on my side, I will work on getting this into a `.md` file and create a PR. :+1:

**Comment by michaelcurry** [comment]
Apparently I don't have self control... And I took a look into `character.character`.  Thank you for the guide above 🎉 

With `character/character` done... Now it is time to track down all these references.  Feel free to close this issue.  I will keep my notes, and put documentation together once I complete this Character rabbit hole.

```
"alk", // string_id:String
"1", // gacha_odds_weight:Number
"4", // rarity:int (Error Check: between 1 and 5)
"0", // element:int
"Human", // race:Array<String>
"", // character_tag:Array<String>
"0", // speciality_type:int
"Male", // gender:String
"alk", // action_skill:String
"1", // leader_ability:Option {id:Int} || ignored if leader_ability:Option {name:String} is "(None)"
"Path to the Stars", // leader_ability:Option {name:String} || "(None)"
"11", // ability_1:Option Int || "(None)"
"12", // ability_2:Option Int || "(None)"
"13", // ability_3:Option Int || "(None)"
"14", // ability_4:Option Int || "(None)"
"15", // ability_5:Option Int || "(None)"
"16", // ability_6:Option Int || "(None)"
"2", // mana_board_kind:int
"Balance", // stance:String
"1", // dentity_character_id:Option Int || "(None)"
"(None)", // pedestal_image:Option String || "(None)"
"1", // max_evolution_level:int (Error Check: 0 or greater)
"false", // omit_character_quest:Boolean (Error Check: Bool Parse)
"true", // web_site_publish:Boolean (Error Check: Bool Parse)
"1", // obtain_source:int
"1", // mana_node_auto_mode:pinball.common.data.character.CharacterManaNodeAutoMode (Error Check: "0" or "1") || "0" = CharacterManaNodeAutoMode.Auto({Kind:CharacterManaNodeAutoKind,has_board2:bool}) || "1" = CharacterManaNodeAutoMode.Manual
"", // CharacterManaNodeAutoMode.Auto({Kind}) pinball.common.data.character.CharacterManaNodeAutoKind (Error Check: "0" or "1") || "0" = CharacterManaNodeAutoKind.Strong || "1" = CharacterManaNodeAutoKind.Normal
"" // CharacterManaNodeAutoMode.Auto({has_board2}) (Error Check: Bool Parse)
```


`character/chatacter_text` as well...

```
"1": [ // Character ID (ref)
    "Alk", // name:String
    "アルク", // furigana:String
    "A mysterious boy who alights in Starview Village. He has no memory of his past or the world he is from, and he is eager for new knowledge. He is cheery and, oddly enough, a marvelous chef. ", // description:Option String || "(None)"
    "Star Hopper", // nickname:Option String || "(None)"
    "Meteor Break", // skill_name_1:String
    "Generates shock waves, inflicting Fire damage on nearby foes / Increases the attack of all parties", // skill_description_1:String
    "Meteor Break+", // skill_name_2:Option String || "(None)"
    "Generates shock waves, inflicting Fire damage on nearby foes / Increases the attack of all parties", // skill_description_2:Option String || "(None)"
    "Path to the Stars", // leader_ability_name:Option String || "(None)"
    "Ryota Osaka" // voice_actor:Option String || "(None)"
],
```
