### ISSUE TITLE
Some gifs of character have strange colors

### ISSUE THREAD

**Issue by wingzhingling** [ScripterSugar/wdfp-extractor#20]
Thank you for your powerful program.I want to get some gifs of characters,but some gifs' color is different from the sprite pics.

There is nothing wrong with `pixelart/animated/special.gif`,but `pixelart/animated/walk_front.gif` and `pixelart/animated/walk_back.gif`  have strange colors.

The pictures below show the difference.The picture on the left is from `pixelart/animated/walk_front.gif`,the picture on the left is from `pixelart/sprite_sheet/pixelart0050.png`.
The gif looks noticeably dimmer.

![image](https://user-images.githubusercontent.com/9023663/210238299-1bc39ae0-d2c3-41ab-bd7e-1c403adad7bd.png)

**Comment by ScripterSugar** [comment]
Hmm, I think I messed up with default gif creation arguments in last update. I'll look into the issue this weekend.

Can you try the animate command with scale option to see if it outputs with better color supports?

If you used delta extraction for 1.641.30 use
`animate -delta 1.641.30 -scale 4 -character psychic_yuki_ny23` 
otherwise
`animate -scale 4 -character psychic_yuki_ny23`

let me know if it temporarily resolves the issue, thanks!

tip: refer to [the documentation](https://github.com/ScripterSugar/wdfp-extractor/blob/master/COMMAND.md) to see how to use commands

**Comment by wingzhingling** [comment]
Thank you for your quick reply.I tried the command and it works.The colors are now displayed correctly.

![image](https://user-images.githubusercontent.com/9023663/210255005-c0c1090f-0e16-4c6a-bd7d-d2feedc53dff.png)

**Comment by ScripterSugar** [comment]
Closed by #21
